name = "render-queue"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "splat-assets"

[[d1_databases]]
binding = "DB"
database_name = "splat-jobs"
database_id = "62434e9d-5628-4378-b198-9050dbf870ee"

# Set via `wrangler secret put WORKER_API_KEY`
# [vars]
# WORKER_API_KEY = "..." # Do NOT put secrets here; use `wrangler secret`
